### ISSUE TITLE
Bug: Error on registration form

### ISSUE THREAD

**Issue by CodeAlDente** [terminal42/contao-mailusername#8] opened 2015-07-11 14:21 UTC
When I try to register, I get the following error:

> Fatal error: Uncaught exception Exception with message Query error: Column 'username' cannot be null (INSERT INTO tl_version (pid, tstamp, version, fromTable, username, userid, description, editUrl, active, data) VALUES ('14', '1436624381', 1, 'tl_member', NULL, 0, 'John Doe', 'contao/main.php?do=member&act=edit&id=14&rt=1', 1,.....

`#2 system/modules/core/classes/Versions.php(135): Contao\Versions->create()
#3 system/modules/core/modules/ModuleRegistration.php(453): Contao\Versions->initialize()
#4 system/modules/core/modules/ModuleRegistration.php(304): Contao\ModuleRegistration->createNewUser(Array)
#5 system/modules/core/modules/Module.php(282): Contao\ModuleRegistration->compile()
#6 system/modules/core/modules/ModuleRegistration.php(58): Contao\Module->generate()
#7 system/modules/core/elements/ContentModule.php(59): Contao\ModuleRegistration->generate()
#8 system/modules/core/library/Contao/Controller.php(476): Contao\ContentModule->generate()
#9 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#10 system/modules/core/modules/Module.php(282): Contao\ModuleArticle->compile()
#11 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#12 system/modules/core/library/Contao/Controller.php(409): Contao\ModuleArticle->generate(false)
#13 system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), true, false, 'main')
#14 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#15 system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#16 index.php(20): Contao\FrontendIndex->run()
#17 {main}`

**I'm using Contao 3.5.0 with the latest version of this plugin (1.0.3.9011) from the contao legacy package.**

Since it worked fine in previous Contao versions, it seems like that they have added something to the master code that makes it now impossible to use this nice plugin. I really hope you can help out here.

**Comment by qzminski** [comment] 2015-07-13 06:16
This has been fixed in 1.0.4 @aschempp please merge it.

https://github.com/terminal42/contao-mailusername/tree/hotfix/1.0.4

**Comment by aschempp** [comment] 2015-07-13 06:34
Duplicate of #7

**Closed by aschempp** 2015-07-13 06:34 UTC
