### ISSUE TITLE
Change "Username" in forms to "E-Mail"

### ISSUE THREAD

**Issue by CodeAlDente** [terminal42/contao-mailusername#10] opened 2015-08-06 02:54 UTC
It could confuse people if the login form asks for an username when you actually need to enter your e-mail address. Therefore you should consider to change the label for this in the appropriate forms (login, password recover etc.) or within the DCA configuration file.

Of course, this is a very low priority request, but few minutes of your work would make the whole thing more user friendly.

**Comment by aschempp** [comment] 2015-08-06 08:38
That should already be the case. Which version did you install?

**Comment by CodeAlDente** [comment] 2015-08-06 09:25
Thanks for your reply.

I've seen the line in the default.php but it still doesn't work. I've checked it twice. I'm using the latest version 1.0.4.9006 along with the newest version of Contao.

**Comment by Total-Reality** [comment] 2015-09-02 15:32
Hmm it is the same like here?! https://github.com/terminal42/contao-mailusername/issues/10

**Comment by CodeAlDente** [comment] 2015-10-10 00:59
Are you guys with me? I still need to fix this. Any idea is appreciated.

**Comment by Toflar** [comment] 2015-10-19 13:08
I can confirm that there's an issue. I tried to find out where it comes from for like 2 hours now but I just cannot find the problem. Probably I'll have some project some day where I need to figure it out but for now you just have to live with the issue or find the source of the problem yourself. I can't help you for now.

**Comment by aschempp** [comment] 2015-10-20 07:03
Maybe we should revert https://github.com/terminal42/contao-mailusername/commit/395592478762986e4cadcdd891fdef56ab3233b6 to fix the problem? Apparently the link does not work as expected, because loading the language files of the second language will override both versions…

**Comment by Toflar** [comment] 2015-10-20 10:35
Maybe. But funnily enough, my debugging session showed that `MSC.emailAddress` contains `Username` which would be the wrong way around?!

**Comment by aschempp** [comment] 2015-10-22 20:10
I know, thats the problem. I guess that happens due to the "link" between the two labels. When the `username` variable is set again (due to loading a second language), it also overrides the email field.

**Comment by Total-Reality** [comment] 2015-10-23 13:26
What can I do to solve this Problem temporarily?
Look at the 4th box on the right side please:
https://www.fast-end-media.de/produkte/

**Comment by Toflar** [comment] 2015-10-23 15:35
Find the issue and fix it? :D

**Comment by Total-Reality** [comment] 2015-10-31 14:34
???? 
Can you answer here please?
https://github.com/terminal42/contao-mailusername/issues/9

**Comment by aschempp** [comment] 2015-10-31 15:29
Please read https://www.terminal42.ch/en/open-source.html

**Comment by Total-Reality** [comment] 2015-10-31 15:49
What does that mean?

**Comment by Total-Reality** [comment] 2015-10-31 16:13
I found the reason of this bug...

Please change system/modules/mailusername/languages/en 

Before: 
$GLOBALS['TL_LANG']['MSC']['username'] = &$GLOBALS['TL_LANG']['MSC']['emailAddress'];

After: 
$GLOBALS['TL_LANG']['MSC']['username'] = $GLOBALS['TL_LANG']['MSC']['emailAddress'];

**Comment by aschempp** [comment] 2015-11-02 12:18
Thanks for the input! I think this would only work for english though. Did you try other languages?

**Comment by CodeAlDente** [comment] 2015-11-02 12:28
I've tried it in other languages, but it does only work if you change it for English. Maybe there is a problem with detecting / setting the language?

**Comment by Total-Reality** [comment] 2015-11-03 09:22
Andreas: No my Website Language is "de" / German. Strange to say but the code change I posted above results in correctness in the german website/language.

**Comment by aschempp** [comment] 2015-11-05 16:32
Should be fixed in 9398d005c21e4a9c4af57b81cf9a78a97ff3cc85

**Closed by aschempp** 2015-11-05 16:32 UTC
Labels: bug

**Comment by CodeAlDente** [comment] 2015-11-14 23:11
It is, thank you!

**Comment by Total-Reality** [comment] 2015-11-25 11:36
Yeah, thank you very much :)
